force-app/main/default/objects/Log__e/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <description>This is the Data</description>
    <label>Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/Quiddity__c.field-meta.xml
<CustomField>
    <fullName>Quiddity__c</fullName>
    <label>Quiddity</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/Running_User__c.field-meta.xml
<CustomField>
    <fullName>Running_User__c</fullName>
    <label>Running User</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <label>Severity</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <label>Transaction Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__c/Log_Event__c.object-meta.xml
<CustomObject>
    <label>Log Event</label>
    <nameField>
        <displayFormat>LOG-{00000000}</displayFormat>
        <label>Log Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log_Event__c/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <description>This is the Data</description>
    <label>Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Event__c/fields/Quiddity__c.field-meta.xml
<CustomField>
    <fullName>Quiddity__c</fullName>
    <label>Quiddity</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__c/fields/Running_User__c.field-meta.xml
<CustomField>
    <fullName>Running_User__c</fullName>
    <label>Running User</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <label>Severity</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__c/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <label>Transaction Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LogTriggerHandler.cls
/**
* @author tomcarman 
* @description Platform Event Trigger handler on Log__e
*/
public class LogTriggerHandler {
    
    public void onAfterInsert(List<Log__e> triggerNewList){

        List<Log_Event__c> logsToStore = new List<Log_Event__c>();

        for(Log__e logEvent : triggerNewList) {
            
            logsToStore.add(
                new Log_Event__c(
                    Data__c = logEvent.Data__c,
                    Location__c = logEvent.Location__c,
                    Quiddity__c = logEvent.Quiddity__c,
                    Transaction_Id__c = logEvent.Transaction_Id__c,
                    Running_User__c = logEvent.Running_User__c,
                    Severity__c = logEvent.Severity__c,
                    Type__c = logEvent.Type__c
                )
            );
        }


        // Logging code should be non-blocking (even if its in its own Platform Event transaction), so 
        // allow it to error and output to debug.
        List<Database.SaveResult> saveResults = Database.insert(logsToStore, false);
        for(Database.SaveResult saveResult : saveResults) {
            if(!saveResult.isSuccess()) {
                System.debug('A Log__e was published, but failed to save due to the following error(s):');
                for(Database.Error error : saveResult.getErrors()) {
                    System.debug(error.getMessage());
                }
            }
        }

    }

}